############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "elements/"
weight = 3

[[main]]
weight = 4
name = "Work"
hasChildren = true

[[main]]
parent = "Machine Learning"
name = "Blog"
url = "blog/"

[[main]]
parent = "Quantum MAchine Learning"
name = "Contact"
url = "contact/"

[[main]]
parent = "Quantum Cryptography"
name = "Authors"
url = "authors/"

[[main]]
parent = "Quantum Algorithms"
name = "Categories"
url = "categories/"

[[main]]
parent = "Quantum meachnics"
name = "404 Page"
url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
