############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
weight = 4
name = "Work"
hasChildren = true

[[main]]
parent = "Work"
name = "Machine Learning"
url = "ML/"

[[main]]
parent = "Work"
name = "Quantum MAchine Learning"
url = "QML/"

[[main]]
parent = "Work"
name = "Quantum Cryptography"
url = "Crypt/"

[[main]]
parent = "Work"
name = "Quantum Algorithms"
url = "Qalgo/"

[[main]]
parent = "Work"
name = "Quantum meachnics"
url = "QMech/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "Blog/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3
