############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About me"
url = "about"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
weight = 4
name = "Work"
hasChildren = true

[[main]]
parent = "Work"
name = "Machine Learning"
url = "ML/"

[[main]]
parent = "Work"
name = "Quantum Machine Learning"
url = "QML/"

# [[main]]
# parent = "Work"
# name = "Quantum Cryptography"
# url = "Crypt/"

[[main]]
parent = "Work"
name = "Quantum Algorithms"
url = "Qalgo/"
weight = 5

[[main]]
name = "Kutty-Story"
url = "Off-Record/"
weight = 6

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3
